from PyQt4 import QtCore, QtGui
from config import *
from myThread import MyThread
from .resultTableClass import ResultTable

####### BEGIN UI code
# code generated by pyuic.bat (pyuic.bat -x spam.ui -o spam.py)
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s
    
class Ui_MyWidget(object):
    def setupUi(self, MyWidget):
        MyWidget.setObjectName(_fromUtf8("MyWidget"))
        MyWidget.resize(802, 634)
        self.horizontalLayout = QtGui.QHBoxLayout(MyWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupParam = QtGui.QGroupBox(MyWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupParam.sizePolicy().hasHeightForWidth())
        self.groupParam.setSizePolicy(sizePolicy)
        self.groupParam.setMinimumSize(QtCore.QSize(300, 0))
        self.groupParam.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupParam.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupParam.setFlat(False)
        self.groupParam.setCheckable(False)
        self.groupParam.setObjectName(_fromUtf8("groupParam"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupParam)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.spinFract = QtGui.QSpinBox(self.groupParam)
        self.spinFract.setMinimum(1)
        self.spinFract.setMaximum(9)
        self.spinFract.setObjectName(_fromUtf8("spinFract"))
        self.verticalLayout_2.addWidget(self.spinFract)
        self.spinMin = QtGui.QSpinBox(self.groupParam)
        self.spinMin.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.spinMin.setSuffix(_fromUtf8(""))
        self.spinMin.setMinimum(-1e9)
        self.spinMin.setMaximum(1e9)
        self.spinMin.setObjectName(_fromUtf8("spinMin"))
        self.verticalLayout_2.addWidget(self.spinMin)
        self.spinMax = QtGui.QSpinBox(self.groupParam)
        self.spinMax.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.spinMax.setMinimum(-1e9)
        self.spinMax.setMaximum(1e9)
        self.spinMax.setProperty("value", 1)
        self.spinMax.setObjectName(_fromUtf8("spinMax"))
        self.verticalLayout_2.addWidget(self.spinMax)
        self.spinNum = QtGui.QSpinBox(self.groupParam)
        self.spinNum.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.spinNum.setMinimum(1)
        self.spinNum.setMaximum(10000)
        self.spinNum.setObjectName(_fromUtf8("spinNum"))
        self.verticalLayout_2.addWidget(self.spinNum)
        self.btnGenerate = QtGui.QPushButton(self.groupParam)
        self.btnGenerate.setObjectName(_fromUtf8("btnGenerate"))
        self.verticalLayout_2.addWidget(self.btnGenerate)
        self.gridLayout.addWidget(self.groupParam, 0, 0, 1, 1)
        self.frame = QtGui.QFrame(MyWidget)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        #self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 458, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(MyWidget)
        QtCore.QMetaObject.connectSlotsByName(MyWidget)

    def retranslateUi(self, MyWidget):
        MyWidget.setWindowTitle(QtGui.QApplication.translate("MyWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupParam.setTitle(QtGui.QApplication.translate("MyWidget", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.spinFract.setPrefix(QtGui.QApplication.translate("MyWidget", "decimal digits - ", None, QtGui.QApplication.UnicodeUTF8))
        self.spinMin.setPrefix(QtGui.QApplication.translate("MyWidget", "min - ", None, QtGui.QApplication.UnicodeUTF8))
        self.spinMax.setSuffix(QtGui.QApplication.translate("MyWidget", " (will not be included)", None, QtGui.QApplication.UnicodeUTF8))
        self.spinMax.setPrefix(QtGui.QApplication.translate("MyWidget", "max - ", None, QtGui.QApplication.UnicodeUTF8))
        self.spinNum.setPrefix(QtGui.QApplication.translate("MyWidget", "numbers - ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGenerate.setText(QtGui.QApplication.translate("MyWidget", "Generate", None, QtGui.QApplication.UnicodeUTF8))

####### END UI code
   
class MyWidget(QtGui.QWidget, Ui_MyWidget, ResultTable):
    def __init__(self, parent=None, master=None):
        QtGui.QWidget.__init__(self, parent)
        self.master = master
        self.error = self.result = self.model = None
        
        self.column = 1
        
        self.setupUi(self)          # set UI (method from Ui_MyWidget)
        ResultTable.__init__(self)  # set UI for result group widget (result table etc...)
        
        self.btnGenerate.clicked.connect(self.generate)
        self.spinCol.valueChanged["int"].connect(self.changeColumn)
        self.btnClear.clicked.connect(self.clearTable)
        self.btnCopy.clicked.connect(self.copyResult)
        self.btnSave.clicked.connect(self.saveResult)
        
        self.thread = MyThread(self, self.getRandom)
        self.thread.finished.connect(self.errorHandler)

    def generate(self):
        self.btnGenerate.setDisabled(True)
        self.thread.start()
        
    def getRandom(self):
        fract = self.spinFract.value()
        num = self.spinNum.value()
        min = self.spinMin.value()
        max = self.spinMax.value()

        # list with only integers  (0, 2, 5, 17...)
        intResult = [min]*num if (min == max-1) else self.master.random.integers(num=num, min=min, max=max-1, base='10', col=1, format='plain', rnd='new')
        
        # list with only decimals (100, 225, 50, 4...)
        fractResult = self.master.random.integers(num=num, min=0, max=(10**fract)-1, base='10', col=1, format='plain', rnd='new')

        # merge 2 lists together (0.100, 2.225, 5.050, 17.004...)
        result = ["{0:.{1}f}".format(int(intResult[i]) + (int(fractResult[i]) / 10**fract), fract) for i in range(num)] # 1 and 23 -> 1.00023 if fract is 5
                
        if self.checkAdd.isChecked() and type(self.result) is list:
            self.result.extend(result)
        else:
            self.result = result

        self.makeTable()

    def log(self, error=None):
        from time import strftime
        self.master.logs.addRow(strftime("%d-%m-%Y"),
                                strftime("%H:%M:%S"),
                                self.master.random.__class__.__name__,
                                "Floats Generator",
                                error if error else "Generated: num=%s min=%s max=%s ndigits=%s" % (self.spinNum.value(), self.spinMin.value(), self.spinMax.value(), self.spinFract.value()))
